export const TEACHERS_LIST_REQUEST = 'TEACHERS_LIST_REQUEST'
export const TEACHERS_LIST_SUCCESS = 'TEACHERS_LIST_SUCCESS'
export const TEACHERS_LIST_FAIL = 'TEACHERS_LIST_FAIL'

export const OPERATORS_LIST_REQUEST = 'OPERATORS_LIST_REQUEST'
export const OPERATORS_LIST_SUCCESS = 'OPERATORS_LIST_SUCCESS'
export const OPERATORS_LIST_FAIL = 'OPERATORS_LIST_FAIL'

export const ADMINS_LIST_REQUEST = 'ADMINS_LIST_REQUEST'
export const ADMINS_LIST_SUCCESS = 'ADMINS_LIST_SUCCESS'
export const ADMINS_LIST_FAIL = 'ADMINS_LIST_FAIL'

export const ACCOUNTANTS_LIST_REQUEST = 'ACCOUNTANTS_LIST_REQUEST'
export const ACCOUNTANTS_LIST_SUCCESS = 'ACCOUNTANTS_LIST_SUCCESS'
export const ACCOUNTANTS_LIST_FAIL = 'ACCOUNTANTS_LIST_FAIL'